[Леванов Валерий] Модуль3-Задача3-ГдеНасНет
MonosUna/algorithms-mipt pull request #10
Opened 2022-12-05 13:51 UTC by MonosUna

https://contest.yandex.ru/contest/39314/run-report/73582993/ - посылка до дедлайна https://contest.yandex.ru/contest/39314/run-report/78811493/ - эта посылка

2022-12-05 16:32 UTC, ibulgakov requested changes

2022-12-05 16:32 UTC, ibulgakov commented on main.cpp
> +  SegmentTree(const int array[], int n) {
vector

2022-12-05 16:32 UTC, ibulgakov commented on main.cpp
> + public:
public размещать выше private

2022-12-05 16:32 UTC, ibulgakov commented on main.cpp
> +  SegmentTree(const int array[], int n) {
explicit еще потом пригодится

2022-12-05 16:32 UTC, ibulgakov commented on main.cpp
> +  int GetAnswer();
const

2022-12-05 16:32 UTC, ibulgakov commented on main.cpp
> +  void FindBigger(int vertex, int l, int r, int x);
const?

2022-12-05 16:32 UTC, ibulgakov commented on main.cpp
> +  int* array = new int[n];
vector

2022-12-05 16:32 UTC, ibulgakov commented on main.cpp
> +    if (tree_[vertex * 2 + 1] >= x && FindLeftVision(2 * vertex + 1) <= r) {
локальную переменную vertex * 2 + 1

2022-12-05 16:32 UTC, ibulgakov commented on main.cpp
> +int SegmentTree::GetAnswer() {
метода не должно быть

2022-12-14 20:49 UTC, vels3113 requested changes

2022-12-14 20:49 UTC, vels3113 commented on 3_C_WhereWe'reNot.cpp
> +  SegmentTree my_struct(array, n);
название переменной должно нести смысл

2022-12-14 20:49 UTC, vels3113 commented on 3_C_WhereWe'reNot.cpp
> +  void MakeChanges(int vertex, int new_value);
лучше назвать Update

2022-12-14 20:49 UTC, vels3113 commented on 3_C_WhereWe'reNot.cpp
> +  int FindBigger(int vertex, int l, int r, int x, int maximum) const;
сделать этот метод приватными вызывать из публичного с простой сигнатурой (FindBigger(vertex, x))

2022-12-18 20:54 UTC, MonosUna commented
https://contest.yandex.ru/contest/39314/run-report/79689927/ - эта посылка

2022-12-21 06:38 UTC, vels3113 approved these changes

2022-12-22 15:45 UTC, closed without merging