[Леванов Валерий] Модуль3-Задача8-ВтораяПорядковаяСтатистика
MonosUna/algorithms-mipt pull request #11
Opened 2022-12-05 14:48 UTC by MonosUna

https://contest.yandex.ru/contest/39314/run-report/73531317/ - посылка до дедлайна https://contest.yandex.ru/contest/39314/run-report/78817739/ - эта посылка

2022-12-05 16:38 UTC, ibulgakov requested changes

2022-12-05 16:38 UTC, ibulgakov commented on main.cpp
> +  int FindMin(int left, int right);
const

2022-12-05 16:38 UTC, ibulgakov commented on main.cpp
> + public:
те же замечания, что и в предыдущей по оформлению класса

2022-12-05 16:38 UTC, ibulgakov commented on main.cpp
> +  SparseTable(int count, int* array) {
vector

2022-12-05 16:38 UTC, ibulgakov commented on main.cpp
> +  SparseTable(int count, int* array) {
переписать эффективно код препроцессинг. 
выделите метод preprocessing()

2022-12-21 06:39 UTC, vels3113 approved these changes

2022-12-22 15:45 UTC, closed without merging