[Леванов Валерий] Модуль6-Задача2-НаибольшаяНевозрастающаяПоследовательность
MonosUna/algorithms-mipt pull request #16
Opened 2023-02-20 14:20 UTC by MonosUna

эта посылка https://contest.yandex.ru/contest/46074/run-report/82680580/

2023-02-26 09:44 UTC, vels3113 requested changes

2023-02-26 09:44 UTC, vels3113 commented on 6B.cpp
> +void PrintAnswer(std::vector<std::pair<int, int>>& dp, int answer,
функция Print... должна только выполнять вывод

2023-02-26 09:44 UTC, vels3113 commented on 6B.cpp
> +  for (int i = 2; i <= count; ++i) {
подсчет дп (т.е. решение) -- в отдельной функции

2023-03-05 20:40 UTC, MonosUna commented
https://contest.yandex.ru/contest/46074/run-report/83480639/

2023-03-11 18:49 UTC, vels3113 requested changes

2023-03-11 18:49 UTC, vels3113 commented on 6B.cpp
> +    std::cin >> num;
ввод отдельно от обработки

2023-03-11 18:49 UTC, vels3113 commented on 6B.cpp
> +  int answer = 1;
непонятная по названию переменная

2023-03-11 18:49 UTC, vels3113 commented on 6B.cpp
> +int FindMaxLengthAndCalculateDP(int count, std::vector<std::pair<int, int>>& dp,
подсчет дп отдельно от определения максимальной длины

2023-03-11 18:49 UTC, vels3113 commented on 6B.cpp
> +void PrintSequence(std::stack<int> order, int max_length) {
лучше называть sequence тот аргумент, который является последовательностью

2023-03-11 18:49 UTC, vels3113 commented on 6B.cpp
> +std::stack<int> FindSequence(std::vector<std::pair<int, int>>& dp,
лучше называть sequence тот аргумент, который является последовательностью

2023-03-29 20:16 UTC, MonosUna commented
https://contest.yandex.ru/contest/46074/run-report/84822077/ - посылка

2023-04-09 14:16 UTC, vels3113 requested changes

2023-04-09 14:16 UTC, vels3113 commented on 6B.cpp
> +int FindMaxLength(int count, std::vector<std::pair<int, int>>& dp,
плохое название функции, оно скрывает, что в ней не только ищется макисмальная длина, но и заполняются позиции. Логичнее вообще отказаться от поиска максимальной длины и посчитать ее, когда уже есть максимальная последовательность, так как это главное искомое в задаче

2023-04-10 16:59 UTC, vels3113 requested changes

2023-04-10 16:59 UTC, vels3113 commented on 6B.cpp
> +  int max_length = 1;
убрать за ненадобностью

2023-04-10 16:59 UTC, vels3113 commented on 6B.cpp
> +  dp[1].first = numbers[1];
PrintStack(FindSequenceIndices(numbers, count))

2023-04-10 16:59 UTC, vels3113 commented on 6B.cpp
> +std::stack<int> FindSequence(std::vector<std::pair<int, int>>& dp,
CreateSequenceIndices()

2023-04-10 16:59 UTC, vels3113 commented on 6B.cpp
> +  dp[1].second = 1;
Комментарий, что в dp[i].first и dp[i].second

2023-04-10 16:59 UTC, vels3113 commented on 6B.cpp
> +  std::cout << max_length << "\n";
перенести в Print

2023-04-11 08:09 UTC, MonosUna commented
https://contest.yandex.ru/contest/46074/run-report/85580403/

2023-04-16 17:12 UTC, vels3113 approved these changes

2023-04-16 17:13 UTC, vels3113 commented
> https://contest.yandex.ru/contest/46074/run-report/85580403/

посылка не прошла

2023-04-21 20:18 UTC, merged