[Леванов Валерий] Модуль6-Задача4-МиссияСамолётов
MonosUna/algorithms-mipt pull request #17
Opened 2023-02-25 14:43 UTC by MonosUna

https://contest.yandex.ru/contest/46074/run-report/82256412/ - посылка

2023-02-26 09:59 UTC, vels3113 requested changes

2023-02-26 09:59 UTC, vels3113 commented on 6D.cpp
> +  int log2 = static_cast<int>(std::log2(floor));
не использовать названия, совпадающие с названиями стандартных функций и т.п.

2023-02-26 09:59 UTC, vels3113 commented on 6D.cpp
> +  std::vector<int> previous_dp(floor + 1, 0);
вынести инициализацию, заполнение ДП и поиск ответа в отдельную функцию

2023-02-26 18:36 UTC, MonosUna commented
https://contest.yandex.ru/contest/46074/run-report/82995689/ - посылка

2023-03-05 15:37 UTC, vels3113 requested changes

2023-03-05 15:37 UTC, vels3113 commented on 6D.cpp
> +int FindAnswer(int floor, int count_of_planes) {
слово answer в названии переменных и функций запрещено (не дает никакого контекста о задаче)

2023-03-05 15:38 UTC, vels3113 requested changes

2023-03-05 15:38 UTC, vels3113 commented on 6D.cpp
> +  std::vector<int> previous_dp(floor + 1, 0);
пояснения в комментарии о том, что хранится в дп

2023-03-05 20:05 UTC, MonosUna commented
https://contest.yandex.ru/contest/46074/run-report/83477247/

2023-03-11 18:37 UTC, vels3113 approved these changes

2023-03-12 08:42 UTC, merged