[Леванов Валерий] Модуль16-Задача2-ОборонаГорода
MonosUna/algorithms-mipt pull request #19
Opened 2023-03-05 20:57 UTC by MonosUna

https://contest.yandex.ru/contest/46074/run-report/83481776/ - посылка

2023-03-11 18:51 UTC, vels3113 requested changes

2023-03-11 18:51 UTC, vels3113 commented on 6P.cpp
> +int CalculateDPFindAnswer(std::vector<std::vector<int>>& matrix, int height,
отдельно подсчет дп, отдельно подсчет того, что требуется по условию (не answer)

2023-03-11 18:51 UTC, vels3113 commented on 6P.cpp
> +  std::cout << CalculateDPFindAnswer(matrix, height, length, mod);
безопаснее height и length получать из размеров matrix

2023-03-17 11:47 UTC, MonosUna commented
https://contest.yandex.ru/contest/46074/run-report/84133132/ - посылка

2023-04-09 13:43 UTC, vels3113 requested changes

2023-04-09 13:43 UTC, vels3113 commented on 6P.cpp
> +  std::vector<int> last_column = CalculateDP(matrix, mod);
комментарий по тому, что и как считается в ДП

2023-04-10 15:20 UTC, MonosUna commented
https://contest.yandex.ru/contest/46074/run-report/85546211/

2023-04-10 15:23 UTC, vels3113 approved these changes

2023-04-10 15:26 UTC, merged