[Леванов Валерий] Модуль7-Задача4-КомпонентыСильнойСвязности
MonosUna/algorithms-mipt pull request #20
Opened 2023-04-18 18:43 UTC by MonosUna

https://contest.yandex.ru/contest/47173/run-report/83610267/ - эты посылка до дл

2023-04-21 20:19 UTC, MonosUna commented
https://contest.yandex.ru/contest/47173/run-report/86176054/

2023-04-23 17:20 UTC, vels3113 requested changes

2023-04-23 17:20 UTC, vels3113 commented on 7D.cpp
> +  int count_of_vertices;
приватные переменные

2023-04-23 17:20 UTC, vels3113 commented on 7D.cpp
> +  std::vector<std::vector<int>> reversed_roads;
переменная алгоритма поиска компонент, а не графа

2023-04-23 17:20 UTC, vels3113 commented on 7D.cpp
> +  Graph(int vertices, int edges, std::vector<std::vector<int>>& roads,
explicit конструктор, который принимает либо вектор ребер, либо количество вершин, а затем добавляет ребра через метод графа

2023-04-23 17:20 UTC, vels3113 commented on 7D.cpp
> +  std::vector<int> top_sorted = TopSort(graph);
метод поиска компонент

2023-04-23 17:20 UTC, vels3113 commented on 7D.cpp
> +void Kosaraju(int count_of_vertices, Graph& graph,
плохое название функции, не говорит о том, что происходит в функции

2023-04-23 17:20 UTC, vels3113 commented on 7D.cpp
> +  Print(group - 1, components);
вывод в main

2023-04-30 20:33 UTC, MonosUna commented
https://contest.yandex.ru/contest/47173/run-report/86776213/

2023-05-07 15:37 UTC, vels3113 requested changes

2023-05-07 15:37 UTC, vels3113 commented on 7D.cpp
> + private:
private ниже public

2023-05-07 15:37 UTC, vels3113 commented on 7D.cpp
> +    std::vector<std::vector<int>> reversed_roads(count_of_vertices_ + 1);
вынести тело метода из функции

2023-05-07 15:37 UTC, vels3113 commented on 7D.cpp
> +void DFS(int vertex, Graph& graph, int& time,
ссылка на константный граф

2023-05-07 15:37 UTC, vels3113 commented on 7D.cpp
> +  std::vector<int> ans;
нельзя так называть переменные

2023-05-07 15:37 UTC, vels3113 commented on 7D.cpp
> +std::vector<int> TopSort(Graph& graph) {
константная ссылка

2023-05-07 15:37 UTC, vels3113 commented on 7D.cpp
> +void DfsKosaraju(int vertex, Graph& graph, std::vector<VertexInfo>& vertices,
название должно объяснять, что делает метод

2023-05-07 15:37 UTC, vels3113 commented on 7D.cpp
> +    int count_of_vertices, Graph& graph, std::vector<int>& top_sorted) {
константные ссылки

2023-05-07 15:37 UTC, vels3113 commented on 7D.cpp
> +  std::vector<int> top_sorted = TopSort(graph);
комментарий проигнорирован?

2023-05-07 15:51 UTC, MonosUna commented on 7D.cpp
> +  std::vector<int> top_sorted = TopSort(graph);
у меня же есть SearchConnectivityComponents

2023-05-08 17:38 UTC, MonosUna commented
https://contest.yandex.ru/contest/47173/run-report/87069953/

2023-05-09 07:38 UTC, vels3113 commented on 7D.cpp
> +  std::vector<int> top_sorted = TopSort(graph);
TopSort часть этого метода?

2023-05-09 07:41 UTC, vels3113 requested changes
(комментарий для гитхаба)

2023-05-12 11:22 UTC, MonosUna commented on 7D.cpp
> +  std::vector<int> top_sorted = TopSort(graph);
> TopSort часть этого метода, сам метод принимает только объект графа

честно не очень понял, я сделал теперь их методами графа. Один приваный, другой публичный

2023-05-12 11:24 UTC, MonosUna commented
https://contest.yandex.ru/contest/47173/run-report/87199592/ - посылка

2023-05-14 15:31 UTC, vels3113 approved these changes

2023-05-16 17:49 UTC, merged