[Леванов Валерий] Модуль7-Задача5-Мосты
MonosUna/algorithms-mipt pull request #21
Opened 2023-04-18 18:53 UTC by MonosUna

https://contest.yandex.ru/contest/47173/run-report/83702421/ - эта посылка до дл

2023-04-23 17:03 UTC, vels3113 requested changes

2023-04-23 17:03 UTC, vels3113 commented on 7E.cpp
> +  std::vector<std::vector<std::pair<int, int>>> roads;
поля относятся к методу поиска мостов и должны храниться там

2023-04-23 17:03 UTC, vels3113 commented on 7E.cpp
> +  int count_of_edges;
это приватные поля, которые достаются гет методами

2023-04-23 17:03 UTC, vels3113 commented on 7E.cpp
> +  void PrintBridges() {
вывод -- не метод графа

2023-04-23 17:03 UTC, vels3113 commented on 7E.cpp
> +  Graph(int vertices, int edges, std::vector<std::vector<std::pair<int, int>>>& roads,
explicit

2023-04-23 17:03 UTC, vels3113 commented on 7E.cpp
> +  for (int i = 1; i < count_of_vertex; ++i) {
должен быть метод поиска мостов

2023-04-30 21:23 UTC, MonosUna commented
https://contest.yandex.ru/contest/47173/run-report/86777890/

2023-05-07 15:44 UTC, vels3113 requested changes

2023-05-07 15:44 UTC, vels3113 commented on 7E.cpp
> +  std::vector<int> FindBridges(std::vector<VertexInfo>& vertices);
зачем методу поиска мостов в классе графа принимать какой-либо аргумент?

2023-05-07 15:44 UTC, vels3113 commented on 7E.cpp
> + private:
private ниже public

2023-05-07 15:44 UTC, vels3113 commented on 7E.cpp
> +void DFS(std::pair<int, int> edge, Graph& G, std::vector<int>& bridges, std::vector<VertexInfo>& vertices, int& time) {
константная ссылка на граф

2023-05-08 17:43 UTC, MonosUna commented
https://contest.yandex.ru/contest/47173/run-report/87070107/

2023-05-09 08:03 UTC, vels3113 approved these changes

2023-05-12 11:33 UTC, merged