[Леванов Валерий] Модуль8-Задача1-ПодлыеКарты
MonosUna/algorithms-mipt pull request #22
Opened 2023-04-18 18:54 UTC by MonosUna

https://contest.yandex.ru/contest/47756/run-report/84800637/ - эта посылка до дл

2023-04-23 18:08 UTC, vels3113 requested changes

2023-04-23 18:08 UTC, vels3113 commented on 8A.cpp
> +  int count_of_vertices;
переменные в приватные поля

2023-04-23 18:08 UTC, vels3113 commented on 8A.cpp
> +#include <iostream>
условие

2023-04-23 18:08 UTC, vels3113 commented on 8A.cpp
> +  Graph(int count_of_vertices,
explicit

2023-04-23 18:08 UTC, vels3113 commented on 8A.cpp
> +std::vector<int> CalculateMinimalDistances(Graph& graph, int vertex,
константная ссылка

2023-05-07 15:48 UTC, vels3113 requested changes

2023-05-07 15:48 UTC, vels3113 commented on 8A.cpp
> + private:
private ниже public

2023-05-08 17:48 UTC, MonosUna commented
https://contest.yandex.ru/contest/47756/run-report/87070252/

2023-05-09 08:06 UTC, vels3113 approved these changes

2023-05-12 11:32 UTC, merged