[Леванов Валерий] Модуль8-Задача5-ЦиклическийСаботаж
MonosUna/algorithms-mipt pull request #23
Opened 2023-04-18 18:58 UTC by MonosUna

https://contest.yandex.ru/contest/47756/run-report/84986112/ - эта посылка до дл

2023-04-23 18:11 UTC, vels3113 requested changes

2023-04-23 18:11 UTC, vels3113 commented on 8E.cpp
> +int CheckForNegativeCycle(std::vector<std::vector<int>>& dp, int count) {
const ссылка

2023-04-23 18:11 UTC, vels3113 commented on 8E.cpp
> +std::vector<int> FindCycle(std::vector<std::vector<int>>& positions, int start,
const ссылка

2023-04-23 18:11 UTC, vels3113 commented on 8E.cpp
> +  dp[0][0] = 0;
комментарий к дп

2023-04-23 18:11 UTC, vels3113 commented on 8E.cpp
> +#include <iostream>
условие

2023-04-23 18:11 UTC, vels3113 commented on 8E.cpp
> +  auto cycle = CalculateDp(graph, kMaxValue);
плохое название функции

2023-04-23 18:11 UTC, vels3113 commented on 8E.cpp
> +  Graph(int count_of_vertices, std::vector<std::vector<int>>& roads)
explicit

2023-04-23 18:11 UTC, vels3113 commented on 8E.cpp
> +  int count_of_vertices;
переменные в приватную область

2023-05-07 15:53 UTC, vels3113 requested changes

2023-05-07 15:53 UTC, vels3113 commented on 8E.cpp
> +struct Graph {
class

2023-05-07 15:53 UTC, vels3113 commented on 8E.cpp
> + private:
private ниже public

2023-05-07 15:53 UTC, vels3113 commented on 8E.cpp
> +int CheckForNegativeCycle(std::vector<std::vector<int>>& dp, int count) {
это не просто check, так как возвращается некоторое используемое впоследствии значение. Назвать это значение и метод соответствующе

2023-05-07 15:53 UTC, vels3113 commented on 8E.cpp
> +std::vector<int> CalculateDPandReturnCycle(const Graph& graph, int max_value) {
отдельный метод должен делать что-то одно

2023-05-08 18:08 UTC, MonosUna commented
https://contest.yandex.ru/contest/47756/run-report/87070805/

2023-05-09 08:24 UTC, vels3113 requested changes

2023-05-09 08:24 UTC, vels3113 commented on 8E.cpp
> +int FindVertexInNegativeCycle(std::vector<std::vector<int>>& dp, int count) {
Константная ссылка

2023-05-09 08:24 UTC, vels3113 commented on 8E.cpp
> +std::vector<int> FindCycle(const std::vector<std::vector<int>>& positions,
По смыслу метод составляет цикл, а не совершает его поиск

2023-05-09 08:24 UTC, vels3113 commented on 8E.cpp
> +  auto pair = CalculateDPandPrevious(graph, max_value);
Сделать пару структурой (например, distanceInfo) и назвать поля по смыслу (дп ‐ расстояния по количеству ребер, previous - вершина, через которую пришли из 1 в 2)

2023-05-12 11:47 UTC, MonosUna commented
https://contest.yandex.ru/contest/47756/run-report/87200917/

2023-05-14 15:35 UTC, vels3113 approved these changes

2023-05-16 17:49 UTC, merged