[Леванов Валерий] Модуль9-ЗадачаI-Минимальное контролирующее множество
MonosUna/algorithms-mipt pull request #24
Opened 2023-05-15 12:42 UTC by MonosUna

https://contest.yandex.ru/contest/48602/run-report/86983441/

2023-05-15 14:17 UTC, MonosUna commented
https://contest.yandex.ru/contest/48602/run-report/87331155/

2023-05-15 15:11 UTC, ibulgakov requested changes

2023-05-15 15:11 UTC, ibulgakov commented on 9I.cpp
> +void dfs(int vertex, std::vector<bool>& used,
класс графа

2023-05-16 18:11 UTC, MonosUna commented
https://contest.yandex.ru/contest/48602/run-report/87382760/

2023-05-22 19:17 UTC, vels3113 approved these changes

2023-05-22 19:28 UTC, merged