[Леванов Валерий] Модуль9-ЗадачаB-MST
MonosUna/algorithms-mipt pull request #25
Opened 2023-05-15 12:43 UTC by MonosUna

https://contest.yandex.ru/contest/48602/run-report/86810912/

2023-05-15 15:09 UTC, ibulgakov requested changes

2023-05-15 15:09 UTC, ibulgakov commented on 9B.cpp
> + public:
секция pubic перед private

2023-05-16 17:47 UTC, MonosUna commented
https://contest.yandex.ru/contest/48602/run-report/87381799/

2023-05-22 19:15 UTC, vels3113 approved these changes

2023-05-22 19:28 UTC, merged