[Леванов Валерий] Модуль9-ЗадачаO-Ядро толпы
MonosUna/algorithms-mipt pull request #26
Opened 2023-05-15 12:44 UTC by MonosUna

https://contest.yandex.ru/contest/48602/run-report/87181182/

2023-05-15 13:56 UTC, MonosUna commented
https://contest.yandex.ru/contest/48602/run-report/87330159/

2023-05-15 15:20 UTC, ibulgakov requested changes

2023-05-15 15:20 UTC, ibulgakov commented on 9O.cpp
> +void bfs(std::vector<VertexInfo>& vertices, const std::vector<Edge>& edges) {
поместить как приватные методы в Network

2023-05-15 15:20 UTC, ibulgakov commented on 9O.cpp
> +struct VertexInfo {
тоже приватная структура?

2023-05-16 18:26 UTC, MonosUna commented
https://contest.yandex.ru/contest/48602/run-report/87383433/

2023-05-22 19:22 UTC, vels3113 requested changes

2023-05-22 19:22 UTC, vels3113 commented on 9O.cpp
> +std::vector<int> FindMaxDensitySubgraph(
метод от графа

2023-05-22 19:22 UTC, vels3113 commented on 9O.cpp
> +class Network {
отсутствует интерфейс графа

2023-05-22 20:46 UTC, MonosUna commented
https://contest.yandex.ru/contest/48602/run-report/87605675/

2023-05-22 21:03 UTC, vels3113 approved these changes

2023-05-22 21:04 UTC, merged