First try of PR
MonosUna/algorithms-mipt pull request #3
Opened 2022-10-10 19:10 UTC by MonosUna

https://contest.yandex.ru/contest/39305/run-report/70848527/
"Сейчас, надеюсь, 1 файл пошлётся."

2022-10-19 15:22 UTC, vels3113 requested changes

2022-10-19 15:22 UTC, vels3113 commented on main.cpp
> +void DoHardInput(deque<int>& first, deque<int>& second, int& count,
разделение на функции должно быть осмысленно с точки зрения пользователя, читаемости кода, особенностей языка и платформы, где запускается программа. Сложность функций (особенно в категориях easy/hard) не попадает под эти концепты, такое только в комментариях можно упоминуть

2022-10-20 15:03 UTC, vels3113 requested changes

2022-10-25 00:00 UTC, ibulgakov requested changes

2022-10-25 00:00 UTC, ibulgakov commented on main.cpp
> +#include <deque>
Нет комментариям перед задачей с условием

2022-10-25 00:00 UTC, ibulgakov commented on main.cpp
> +    std::cin >> number_of_goblin;
Ввод-вывод в main

2022-10-28 20:18 UTC, MonosUna commented
https://contest.yandex.ru/contest/39305/run-report/70848527/ первая посылка
https://contest.yandex.ru/contest/39305/run-report/72966698/ текущая посылка

2022-10-28 20:19 UTC, ibulgakov approved these changes

2022-10-28 20:44 UTC, merged