First try of PR
MonosUna/algorithms-mipt pull request #6
Opened 2022-10-24 18:46 UTC by MonosUna

https://contest.yandex.ru/contest/39313/run-report/72781558/ дедлайн 
 https://contest.yandex.ru/contest/39313/run-report/72949571/ актуальная посылка

2022-11-12 11:57 UTC, vels3113 requested changes

2022-11-12 11:57 UTC, vels3113 commented on main.cpp
> +  void DoSwapInMin(int vertex1, int vertex2);
не надо Do, Swap это глагол

2022-11-12 11:57 UTC, vels3113 commented on main.cpp
> +void MiniMax::DoRequest(std::string request) {
все-таки, это должно быть функцией, а не методом. Структуре данных не надо знать, как могут вводить команды на работу с ней, она должна только отрабатывать логику запросов

2022-11-12 11:57 UTC, vels3113 commented on main.cpp
> +  mini_max.min_heap = array;
инициализация должна быть внутри структуры данных

2022-11-12 11:57 UTC, vels3113 commented
Разобраться с конфликтом

2022-11-26 19:02 UTC, vels3113 requested changes

2022-11-26 19:02 UTC, vels3113 commented on main.cpp
> +  void DoClear();
не надо Do

2022-12-04 11:58 UTC, vels3113 requested changes

2022-12-04 11:58 UTC, vels3113 commented on main.cpp
> +  void DoSwapInMin(int vertex1, int vertex2);
поправить

2022-12-04 11:58 UTC, vels3113 commented on main.cpp
> +  void DoSwapInMax(int vertex1, int vertex2);
выделить приватные методы

2022-12-05 16:44 UTC, ibulgakov requested changes

2022-12-11 11:06 UTC, vels3113 approved these changes

2022-12-18 14:16 UTC, closed without merging