[Леванов Валерий] Модуль2-Задача3-УменьшениеКлюча
MonosUna/algorithms-mipt pull request #8
Opened 2022-11-14 19:40 UTC by MonosUna

https://contest.yandex.ru/contest/39313/run-report/72349094/ - эта посылка до дедлайна

2022-11-26 18:53 UTC, vels3113 requested changes

2022-11-26 18:53 UTC, vels3113 commented on main.cpp
> +void SiftDown(long long* array, const int kSize, int current_element) {
структура/класс кучи

пустые строки между функциями/структурами

2022-12-04 12:32 UTC, vels3113 requested changes

2022-12-04 12:32 UTC, vels3113 commented on main.cpp
> +  void SiftDown(int current_element);
приватные методы

2022-12-04 12:32 UTC, vels3113 commented on main.cpp
> +};
пустые строки между телами

2022-12-05 16:43 UTC, ibulgakov requested changes

2022-12-05 16:43 UTC, ibulgakov commented on main.cpp
> +    int descendant = 2 * current_element;
ввести переменные левый сын и правый сын и их использовать в коде

2022-12-05 16:43 UTC, ibulgakov commented on main.cpp
> +  Heap(int count) {
explicit, const, public выше private

2022-12-05 16:43 UTC, ibulgakov commented on main.cpp
> +      ptr_[i] = 1'000'000'001;
не надо под задачу константы

2022-12-11 11:00 UTC, vels3113 approved these changes

2022-12-18 14:15 UTC, closed without merging