[Леванов Валерий] Модуль2-Задача7-ПоразряднаяСортировка
MonosUna/algorithms-mipt pull request #9
Opened 2022-11-14 20:04 UTC by MonosUna

https://contest.yandex.ru/contest/39313/run-report/72716293/ - посылка до дедлайна https://contest.yandex.ru/contest/39313/run-report/74863991/ - эта посылка

2022-11-26 18:59 UTC, vels3113 requested changes

2022-11-26 18:59 UTC, vels3113 commented on main.cpp
> +void BigInteger::SortBasket() {
это не поразрядная сортировка

https://algolist.ru/sort/radix_sort.php

2022-11-26 18:59 UTC, vels3113 commented on main.cpp
> +  void GiveAnswer();
таких названий не должно быть

2022-11-26 18:59 UTC, vels3113 commented on main.cpp
> +struct BigInteger {
структура скорее всего не нужна, так как сортируем в том же массиве, что и заполняли

2022-12-05 16:47 UTC, ibulgakov requested changes

2022-12-05 16:47 UTC, ibulgakov commented on main.cpp
> +  for (int j = 0; j < 4; j++) {
поработать над функциональной декомпозицией

1. Считать данные в main
2. Вызвать функцию сортировки Sort(vector?)

2022-12-17 15:38 UTC, vels3113 commented
Это не сортировка по байтам

2023-02-20 10:10 UTC, closed without merging